export default {
  "england-and-wales": {
    division: "england-and-wales",
    events: [
      {
        title: "Summer bank holiday",
        date: "2021-08-30",
        notes: "",
        bunting: true,
      },
      {
        title: "Christmas Day",
        date: "2021-12-27",
        notes: "Substitute day",
        bunting: true,
      },
      {
        title: "Boxing Day",
        date: "2021-12-28",
        notes: "Substitute day",
        bunting: true,
      },
      {
        title: "New Year’s Day",
        date: "2022-01-03",
        notes: "Substitute day",
        bunting: true,
      },
      {
        title: "Good Friday",
        date: "2022-04-15",
        notes: "",
        bunting: false,
      },
      {
        title: "Easter Monday",
        date: "2022-04-18",
        notes: "",
        bunting: true,
      },
      {
        title: "Early May bank holiday",
        date: "2022-05-02",
        notes: "",
        bunting: true,
      },
      {
        title: "Spring bank holiday",
        date: "2022-06-02",
        notes: "",
        bunting: true,
      },
      {
        title: "Platinum Jubilee bank holiday",
        date: "2022-06-03",
        notes: "",
        bunting: true,
      },
      {
        title: "Summer bank holiday",
        date: "2022-08-29",
        notes: "",
        bunting: true,
      },
    ],
  },
  scotland: {
    division: "scotland",
    events: [
      {
        title: "Summer bank holiday",
        date: "2021-08-02",
        notes: "",
        bunting: true,
      },
      {
        title: "St Andrew’s Day",
        date: "2021-11-30",
        notes: "",
        bunting: true,
      },
      {
        title: "Christmas Day",
        date: "2021-12-27",
        notes: "Substitute day",
        bunting: true,
      },
      {
        title: "Boxing Day",
        date: "2021-12-28",
        notes: "Substitute day",
        bunting: true,
      },
      {
        title: "New Year’s Day",
        date: "2022-01-03",
        notes: "Substitute day",
        bunting: true,
      },
      {
        title: "2nd January",
        date: "2022-01-04",
        notes: "Substitute day",
        bunting: true,
      },
      {
        title: "Good Friday",
        date: "2022-04-15",
        notes: "",
        bunting: false,
      },
      {
        title: "Early May bank holiday",
        date: "2022-05-02",
        notes: "",
        bunting: true,
      },
      {
        title: "Spring bank holiday",
        date: "2022-06-02",
        notes: "",
        bunting: true,
      },
      {
        title: "Platinum Jubilee bank holiday",
        date: "2022-06-03",
        notes: "",
        bunting: true,
      },
      {
        title: "Summer bank holiday",
        date: "2022-08-01",
        notes: "",
        bunting: true,
      },
    ],
  },
  "northern-ireland": {
    division: "northern-ireland",
    events: [
      {
        title: "Summer bank holiday",
        date: "2021-08-30",
        notes: "",
        bunting: true,
      },
      {
        title: "Christmas Day",
        date: "2021-12-27",
        notes: "Substitute day",
        bunting: true,
      },
      {
        title: "Boxing Day",
        date: "2021-12-28",
        notes: "Substitute day",
        bunting: true,
      },
      {
        title: "New Year’s Day",
        date: "2022-01-03",
        notes: "Substitute day",
        bunting: true,
      },
      {
        title: "St Patrick’s Day",
        date: "2022-03-17",
        notes: "",
        bunting: true,
      },
      {
        title: "Good Friday",
        date: "2022-04-15",
        notes: "",
        bunting: false,
      },
      {
        title: "Easter Monday",
        date: "2022-04-18",
        notes: "",
        bunting: true,
      },
      {
        title: "Early May bank holiday",
        date: "2022-05-02",
        notes: "",
        bunting: true,
      },
      {
        title: "Spring bank holiday",
        date: "2022-06-02",
        notes: "",
        bunting: true,
      },
      {
        title: "Platinum Jubilee bank holiday",
        date: "2022-06-03",
        notes: "",
        bunting: true,
      },
      {
        title: "Battle of the Boyne (Orangemen’s Day)",
        date: "2022-07-12",
        notes: "",
        bunting: false,
      },
      {
        title: "Summer bank holiday",
        date: "2022-08-29",
        notes: "",
        bunting: true,
      },
    ],
  },
};
